[bar.default]
background_opacity = 0.84999998100101948
end = [ "tray", "notifications", "clipboard", "network", "volume", "brightness", "session" ]
font_weight = 400
shadow = false
start = [ "workspaces", "media" ]
thickness = 30
widget_spacing = 16

[brightness]
enable_ddcutil = true

[calendar.account.manh1998nb]
type = "google"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "dark_mode"

[dock]
shadow = false

[location]
address = "Vientiane"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@winit", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 961.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 70.0
    box_width = 400.0
    cx = 474.0
    cy = 915.0
    output = "winit"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[nightlight]
enabled = true
temperature_night = 4500

[shell]
font_family = "Noto Sans"
polkit_agent = true

    [shell.panel]
    shadow = false

    [shell.screenshot]
    confirm_region = true
    directory = "/home/paxmix/Pictures/Screenshots"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "destructive"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "5"
    variant = "default"

[system.monitor]
enabled = false

[theme]
builtin = "Tokyo-Night"

    [theme.templates]
    builtin_ids = []

[wallpaper]
directory = "/home/paxmix/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/paxmix/Pictures/Wallpapers/1082113.jpg"

    [wallpaper.last]
    path = "/home/paxmix/Pictures/Wallpapers/1082113.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/paxmix/Pictures/Wallpapers/1082113.jpg"

[weather]
refresh_minutes = 240

[widget.clock]
font_family = "Noto Sans"
font_weight = 600
format = "{:%I:%M %p %A, %d/%m/%Y}"

[widget.workspaces]
hide_when_empty = true
