# | Look & Feel |
# theming | https://mangowm.github.io/docs/visuals

gappih = 5
gappiv = 5
gappoh = 10
gappov = 5
borderpx = 4
border_radius = 8

scratchpad_width_ratio = 0.8
scratchpad_height_ratio = 0.9

cursor_theme = Adwaita
cursor_size = 24

blur = 1
blur_layer = 0
blur_optimized = 1
blur_params_num_passes = 2
blur_params_radius = 5
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.0

shadows = 1
layer_shadows = 0
shadow_only_floating = 0
shadows_size = 4
shadows_blur = 12
shadows_position_x = 2
shadows_position_y = 2

animations = 1
layer_animations = 0
animation_type_open = zoom
animation_type_close = zoom
animation_fade_in = 1
animation_fade_out = 1
tag_animation_direction = 1
zoom_initial_ratio = 0.1
zoom_end_ratio = 0.5
fadein_begin_opacity = 0.3
fadeout_begin_opacity = 0.2
animation_duration_move = 300
animation_duration_open = 100
animation_duration_tag = 300
animation_duration_close = 400
animation_duration_focus = 0
animation_curve_open = 0.87, 0, 0.13, 1
animation_curve_move = 0.46, 1.0, 0.29, 1
animation_curve_tag = 0.46, 1.0, 0.29, 1
animation_curve_close = 0.87, 0, 0.13, 1
animation_curve_focus = 0.46, 1.0, 0.29, 1
animation_curve_opafadeout = 0.5, 0.5, 0.5, 0.5
animation_curve_opafadein = 0.46, 1.0, 0.29, 1
