# | Input Devices |
# Configure your input devices here. | https://mangowm.github.io/docs/configuration/input

# xkb_rules_layout =

repeat_delay = 300

# If you want to disable pointer acceleration, uncomment the lines below.
mouse_accel_profile = 1
mouse_accel_speed = 0.2
