gui:
  theme:
    activeBorderColor:
      - "#A9B665" # green
      - bold

    inactiveBorderColor:
      - "#7C6F64"

    searchingActiveBorderColor:
      - "#D8A657" # yellow
      - bold

    optionsTextColor:
      - "#89B482" # aqua

    selectedLineBgColor:
      - "#32302F"

    selectedRangeBgColor:
      - "#3C3836"

    cherryPickedCommitBgColor:
      - "#3C3836"

    cherryPickedCommitFgColor:
      - "#A9B665"

    unstagedChangesColor:
      - "#EA6962" # red

    defaultFgColor:
      - "#D4BE98"

    inactiveViewSelectedLineBgColor:
      - "#3C3836"

    statusPanelBorderColor:
      - "#7DAEA3" # blue

    branchColor:
      - "#7DAEA3"

    diff:
      addedColor:
        - "#A9B665"
      removedColor:
        - "#EA6962"

    commitHashColor:
      - "#89B482"

    errorColor:
      - "#EA6962"

    warningColor:
      - "#D8A657"
