# | Rules |
# Window/Tag/Layer rules. | https://mangowm.github.io/docs/window-management/rules

windowrule = isfloating:1,istagsilent:1, appid:[Ss]team, tags: 2
windowrule = isfloating:0,istagsilent:1, title:Steam
windowrule = isfloating:1, appid:steam, title:^Steam Settings$
windowrule = isfullscreen:1, appid:steam_app, tags: 3
windowrule = isfullscreen:1, appid:cs2, tags: 3

windowrule = isfloating:1,width:1080,height:920, appid:dev.noctalia.Noctalia

windowrule = appid:firefox, tags:1

windowrule = appid:org.gnome.Nautilus, tags:3
windowrule = isfloating:1, appid:org.gnome.NautilusPreviewer
windowrule = appid:Amberol, tags:4
windowrule = appid:vlc, tags:4


layerrule = noanim:1, noblur:1, layer_name:selection
